= Migration Guide

Migration between minor versions follows the same steps:

. Update `@perfective/eslint-config` and its peer dependencies.
. Disable all new rules.
. Gradually enable the new rules:
** remove one or more rules from the list;
** fix errors or check auto-fixes of warnings;
** check for the regressions.

== From v0.33.0 to v0.34.0

* *Update ESLint configuration*
+
If you use Jest with TypeScript test files,
update your configuration to use the new `jestTypescriptConfig()` for TypeScript-specific rules:
+
.eslint.config.js
[source,javascript]
----
import { perfectiveEslintConfig } from '@perfective/eslint-config';
import { jestConfig, jestTypescriptConfig } from '@perfective/eslint-config/jest';

const eslintConfig = perfectiveEslintConfig([
    jestConfig,
    jestTypescriptConfig, // Add this for TypeScript Jest tests
    // ...other optional plugins configs...
]);

export default eslintConfig;
----
+
If you only use JavaScript for Jest tests,
no changes are required as `jestConfig()` continues to work as before.


== From v0.32.0 to v0.33.0

* *Disable and gradually enable new rules*
+
.eslint.config.js
[source,javascript]
----
import { perfectiveEslintConfig } from '@perfective/eslint-config';

const eslintConfig = perfectiveEslintConfig([
    // ...Optional plugins configs...
    {
        rules: {
            // typescript-eslint
            '@typescript-eslint/no-unused-private-class-members': 'off',
            '@typescript-eslint/no-useless-default-assignment': 'off',
            // eslint-plugin-jsdoc
            'jsdoc/escape-inline-tags': 'off',
            'jsdoc/prefer-import-tag': 'off',
            'jsdoc/reject-any-type': 'off',
            'jsdoc/reject-function-type': 'off',
            'jsdoc/require-next-description': 'off',
            'jsdoc/require-next-type': 'off',
            'jsdoc/require-rejects': 'off',
            'jsdoc/require-throws-description': 'off',
            'jsdoc/require-throws-type': 'off',
            'jsdoc/require-yields-description': 'off',
            'jsdoc/require-yields-type': 'off',
            'jsdoc/ts-method-signature-style': 'off',
            'jsdoc/ts-no-empty-object-type': 'off',
            'jsdoc/ts-no-unnecessary-template-expression': 'off',
            'jsdoc/ts-prefer-function-type': 'off',
            'jsdoc/type-formatting': 'off',
            // eslint-plugin-jest
            'jest/no-error-equal': 'off',
            'jest/no-unnecessary-assertion': 'off',
            'jest/no-unneeded-async-expect-function': 'off',
            'jest/prefer-mock-return-shorthand': 'off',
            'jest/prefer-to-have-been-called': 'off',
            'jest/prefer-to-have-been-called-times': 'off',
            'jest/valid-expect-with-promise': 'off',
            'jest/valid-mock-module-path': 'off',
            // eslint-plugin-testing-library
            'testing-library/prefer-user-event-setup': 'off',
            // eslint-plugin-rxjs-x
            'rxjs-x/no-sharereplay-before-takeuntil': 'off',
            'rxjs-x/no-unnecessary-collection': 'off',
        },
    },
]);

export default eslintConfig;
----


== From v0.31.2 to v0.32.0

* _(If explicitly declared)_ *Update @stylistic ESLint plugin dependencies*:
+
** Add `@stylistic/eslint-plugin` as a dependency.
** Remove `@stylistic/eslint-plugin-js`, `@stylistic/eslint-plugin-jsx`, `@stylistic/eslint-plugin-ts`,
and `@stylistic/eslint-plugin-plus` dependencies.
** Rename customized `@stylistic` rules dependencies:
remove `/js`, `/jsx`, `/ts`, and `/plus` infixes.
+
* *Disable and gradually enable new rules**
+
.eslint.config.js
[source,javascript]
----
import { perfectiveEslintConfig } from '@perfective/eslint-config';

const eslintConfig = perfectiveEslintConfig([
    // ...Optional plugins configs...
    {
        rules: {
            'no-unassigned-vars': 'off',
            '@typescript-eslint/no-unnecessary-type-conversion': 'off',
            'jest/prefer-ending-with-an-expect': 'off',
            'n/no-top-level-await': 'off',
            'testing-library/no-test-id-queries': 'off',
            'unicorn/no-useless-error-capture-stack-trace': 'off',
            'unicorn/prefer-class-fields': 'off',
            'unicorn/require-module-specifiers': 'off',
        },
    },
]);

export default eslintConfig;
----


== From v0.30.0 to v0.31.0

* *Update peer dependencies*
+
_If explicitly configured in `package.json`_
+
** Remove `eslint-plugin-eslint-comments`
+
Add `"@eslint-community/eslint-plugin-eslint-comments": "^4.5.0"`
+
** Remove `@smarttools/eslint-plugin-rxjs`
+
Add `"eslint-plugin-rxjs-x": "~0.7.2"`
+
* *Update imports*
+
** Rules functions from `@perfective/eslint-config/rules` are moved into the corresponding config packages.
** Types and functions from `@perfective/eslint-config/config` are now exported from `@perfective/eslint-config`.
** See `README` for the list of exports.
+
* *Update `eslint.config.js`*
+
** All configs are now functions.
** `perfectiveEslintConfig` is now a regular export.
** Update rules configuration functions imports (see `README.adoc`)
+
.eslint.config.js
[source,javascript]
----
import { perfectiveEslintConfig } from '@perfective/eslint-config';
// Optional dependencies.
import { cypressConfig } from '@perfective/eslint-config/cypress';
import { jestConfig } from '@perfective/eslint-config/jest';
import { jestDomConfig } from '@perfective/eslint-config/jest-dom';
import { rxjsConfig } from '@perfective/eslint-config/rxjs';
import { testingLibraryConfig } from '@perfective/eslint-config/testing-library';

const eslintConfig = perfectiveEslintConfig([
    cypressConfig,
    jestConfig,
    jestDomConfig,
    rxjsConfig,
    testingLibraryConfig,
]);

export default eslintConfig;
----
+
* *Update customized rules* (_if present_):
+
** Change `rxjs-x/no-ignored-observables` to `rxjs-x/no-floating-observables`.
** Change `unicorn/no-array-push-push` to `unicorn/prefer-single-call`.
** Change `unicorn/no-length-as-slice-end` to `unicorn/no-unnecessary-slice-end`.
+
* *Disable and gradually enable new rules*:
+
.eslint.config.js
[source,javascript]
----
import { perfectiveEslintConfig } from '@perfective/eslint-config';

const eslintConfig = perfectiveEslintConfig([
    // ...Optional plugins configs...
    {
        rules: {
            '@typescript-eslint/no-unnecessary-type-assertion': ['warn', {
                checkLiteralConstAssertions: false,
            }],
            'unicorn/prefer-import-meta-properties': 'off',
            'unicorn/no-unnecessary-array-flat-depth': 'off',
            'unicorn/no-unnecessary-array-splice-count': 'off',
        },
    },
]);

export default eslintConfig;
----

== From v0.29.2 to v0.30.0

* *Migrate to ES modules*:
+
** (Optional) If your project does not use ESM by default,
rename `eslint.config.js` into `eslint.config.mjs`.
+
** Update `eslint.config.js` to use ES `import`.
+
.`eslint.config.js`
[source,javascript]
----
import perfectiveEslintConfig from '@perfective/eslint-config';
// Optional dependencies.
import { cypressConfig } from '@perfective/eslint-config/cypress';
import { jestConfig } from '@perfective/eslint-config/jest';
import { jestDomConfig } from '@perfective/eslint-config/jest-dom';
import { rxjsConfig } from '@perfective/eslint-config/rxjs';
import { testingLibraryConfig } from '@perfective/eslint-config/testing-library';

const eslintConfig = [
    ...perfectiveEslintConfig,
    cypressConfig(),
    jestConfig(),
    jestDomConfig(),
    rxjsConfig(),
    testingLibraryConfig(),
];

export default eslintConfig;
----
+
* Disable and gradually enable new rules in the `eslint.config.js`.
+
[source,javascript]
----
import perfectiveEslintConfig from '@perfective/eslint-config';

const eslintConfig = [
    ...perfectiveEslintConfig,
    // ... optional configurations
    {
        files: ['**/*.[jt]s?(x)'],
        rules: {
            '@typescript-eslint/no-misused-spread': 'off',
            'unicorn/consistent-assert': 'off',
            'unicorn/consistent-date-clone': 'off',
            'unicorn/no-accessor-recursion': 'off',
            'unicorn/no-instanceof-builtins': 'off',
            'unicorn/no-named-default': 'off',
            'cypress/no-xpath': 'off',
        },
    }
];

export default eslintConfig;
----


== From v0.28.0 to v0.29.2

* Replace obsolete optional dependency (if used):
** Remove `eslint-plugin-rxjs`
** Add `@smarttools/eslint-plugin-rxjs`
+
* Remove `@babel/eslint-parser` dependency.
+
* *Remove* unused _optional_ dependencies:
+
** `eslint-plugin-cypress`
** `eslint-plugin-jest`
** `eslint-plugin-jest-dom`
** `eslint-plugin-jest-formatting`
** `eslint-plugin-testing-library`
+
* Add ESLint configurations for used _optional_ dependencies:
+
.`eslint.config.js`
[source,javascript]
----
const perfectiveEslintConfig = require('@perfective/eslint-config');
const perfectiveCypressConfig = require('@perfective/eslint-config/cypress');
const perfectiveJestConfig = require('@perfective/eslint-config/jest');
const perfectiveJestDomConfig = require('@perfective/eslint-config/jest-dom');
const perfectiveRxjsConfig = require('@perfective/eslint-config/rxjs');
const perfectiveTestingLibraryConfig = require('@perfective/eslint-config/testing-library');

module.exports = [
    ...perfectiveEslintConfig.default,
    perfectiveCypressConfig.cypressConfig(),
    perfectiveJestConfig.jestConfig(),
    perfectiveJestDomConfig.jestDomConfig(),
    perfectiveRxjsConfig.rxjsConfig(),
    perfectiveTestingLibraryConfig.testingLibrarysConfig(),
];
----
+
* Disable and gradually enable new rules in the `eslint.config.js`.
+
[source,javascript]
----
const perfectiveEslintConfig = require('@perfective/eslint-config');

module.exports = [
    ...perfectiveEslintConfig.default,
    // Optional configurations omitted
    {
        files: ['**/*.[jt]s?(x)'],
        rules: {
            'no-useless-assignment': 'off',
        },
    },
];
----


== From v0.27.1 to v0.28.0

* Remove obsolete peer dependencies:
** `@typescript-eslint/eslint-plugin` (replaced by `typescript-eslint`)
** `@typescript-eslint/parser`
** `eslint-plugin-sonarjs`
+
* *Temporarily* install _optional_ dependencies:
+
** `eslint-plugin-cypress`
** `eslint-plugin-jest
** `eslint-plugin-jest-dom`
** `eslint-plugin-jest-formatting`
** `eslint-plugin-rxjs`
** `eslint-plugin-testing-library`
+
* Rename `.eslintrc.js` into `eslint.config.js`
** Change configuration structure.
+
.Before
[source,javascript]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
}
----
+
.After
[source,javascript]
----
const perfectiveEslintConfig = require('@perfective/eslint-config');

module.exports = perfectiveEslintConfig.default;
----
+
* Disable and gradually enable new rules in the `eslint.config.js`.
+
[source,javascript]
----
const perfectiveEslintConfig = require('@perfective/eslint-config');

module.exports = [
    ...perfectiveEslintConfig.default,
    {
        files: ['**/*.[jt]s?(x)'],
        rules: {
            'promise/prefer-catch': 'off',
        },
    },
];
----


== From v0.26.1 to v0.27.1

* Remove obsolete peer dependencies:
** `tslint`
** `@typescript-eslint/eslint-plugin-tslint`
** `eslint-plugin-jest-formatting`
** `eslint-plugin-deprecation`
+
* Remove deprecated rules, if present in the custom configuration:
** `@typescript-eslint/ban-types`
** `@typescript-eslint/no-loss-of-precision`
** `deprecation/deprecation`
** `jest-formatting/padding-around-after-all-blocks` (use `jest/padding-around-after-all-blocks`)
** `jest-formatting/padding-around-after-each-blocks` (use `jest/padding-around-after-each-blocks`)
** `jest-formatting/padding-around-all` (use `jest/padding-around-all`)
** `jest-formatting/padding-around-before-all-blocks` (use `jest/padding-around-before-all-blocks`)
** `jest-formatting/padding-around-before-each-blocks` (use `jest/padding-around-before-each-blocks`)
** `jest-formatting/padding-around-describe-blocks` (use `jest/padding-around-describe-blocks`)
** `jest-formatting/padding-around-expect-groups` (use `jest/padding-around-expect-groups`)
** `jest-formatting/padding-around-test-blocks` (use `jest/padding-around-test-blocks`)
+
* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-empty-object-type': 'off',
                '@typescript-eslint/no-unnecessary-type-parameters': 'off',
                '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'off',
                '@typescript-eslint/no-deprecated': 'off',
                '@typescript-eslint/no-restricted-types': 'off',
                '@typescript-eslint/no-unsafe-function-type': 'off',
                '@typescript-eslint/no-wrapper-object-types': 'off',
                '@stylistic/plus/curly-newline': 'off',
                'unicorn/consistent-existence-index-check': 'off',
                'unicorn/no-length-as-slice-end': 'off',
                'unicorn/prefer-global-this': 'off',
                'unicorn/prefer-math-min-max': 'off',
                'jsdoc/check-template-names': 'off',
                'jsdoc/require-hyphen-before-param-description': 'off',
                'promise/spec-only': 'off',

                // If eslint-plugin-cypress is installed
                'cypress/no-debug': 'off',
            },
        },
    ],
};
----


== From v0.26.0 to v0.26.1

* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@stylistic/ts/object-curly-newline': 'off',
                '@stylistic/ts/object-property-newline': 'off',
            },
        },
    ],
};
----


== From v0.25.1 to v0.26.0

* Remove `eslint-plugin-node` from `devDependencies`, if present.
+
* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'security/detect-bidi-characters': 'off',
                'security/detect-buffer-noassert': 'off',
                'security/detect-child-process': 'off',
                'security/detect-disable-mustache-escape': 'off',
                'security/detect-eval-with-expression': 'off',
                'security/detect-new-buffer': 'off',
                'security/detect-no-csrf-before-method-override': 'off',
                'security/detect-non-literal-fs-filename': 'off',
                'security/detect-non-literal-regexp': 'off',
                'security/detect-non-literal-require': 'off',
                'security/detect-object-injection': 'off',
                'security/detect-possible-timing-attacks': 'off',
                'security/detect-pseudoRandomBytes': 'off',
                'security/detect-unsafe-regex': 'off',
                'unicorn/no-negation-in-equality-check': 'off',
            },
        },
    ],
};
----


== From v0.24.0 to v0.25.1

* Replace customized `eslint-plugin-node` rules (if any) with `eslint-plugin-n`:
** Replace customized `node/` rules with `n/`.
** Replace `node/shebang` rule with `n/hashbang`.
** Disable `n/no-hide-core-modules` as deprecated.
** Change `n/exports-style` severity to `warn`.
+
* Update customizations (if any) for the deprecated `@typescript-eslint` rules:
** Replace `@typescript-eslint/no-throw-literal` with `@typescript-eslint/only-throw-error`.
** Replace `@typescript-eslint/no-useless-template-literals`
with `@typescript-eslint/no-unnecessary-template-expression`.
** Disabled deprecated `@typescript-eslint/prefer-ts-expect-error`.
+
* Add `@jest/globals` to the `devDependencies` for the `jest/prefer-importing-jest-globals` rule.
+
* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@stylistic/js/line-comment-position': 'off',
                '@stylistic/js/multiline-comment-style': 'off', // Auto-fixable
                '@stylistic/jsx/jsx-function-call-newline': 'off', // Auto-fixable
                '@typescript-eslint/consistent-return': 'off',
                '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
                'cypress/no-async-before': 'off',
                'jest/prefer-importing-jest-globals': 'off', // Auto-fixable
                'jest/prefer-jest-mocked': 'off', // Auto-fixable
                'unicorn/consistent-empty-array-spread': 'off', // Auto-fixable
                'unicorn/no-anonymous-default-export': 'off',
                'unicorn/no-await-in-promise-methods': 'off',
                'unicorn/no-invalid-fetch-options': 'off',
                'unicorn/no-magic-array-flat-depth': 'off',
                'unicorn/no-single-promise-in-promise-methods': 'off', // Auto-fixable
            },
        },
    ],
};
----


== From v0.23.4 to v0.24.0

* Check customizations of the `eslint` and `@typescript-eslint` rules replaced
by the https://eslint.style/rules[ESLint Stylistic rules].
Replace the name of the customized rules with the new rules.
See Stylistic https://eslint.style/guide/migration[migration] documentation for details.
+
* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-array-delete': 'off',
                '@typescript-eslint/prefer-find': 'off',
                '@typescript-eslint/prefer-promise-reject-errors': 'off',
            },
        },
    ],
};
----


== From v0.22.0 to v0.23.4

* Disable and gradually enable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'no-object-constructor': 'off',
                '@typescript-eslint/no-useless-template-literals': 'off',
                '@typescript-eslint/no-unsafe-unary-minus': 'off',
                'jest/no-confusing-set-timeout': 'off',
                'testing-library/prefer-implicit-assert': 'off',
            },
        },
    ],
};
----


== From v0.21.0 to v0.22.0

* Update `eslint-plugin-testing-library` rules:
** Replace `testing-library/await-async-query` with `testing-library/await-async-queries`.
** Replace `testing-library/await-fire-event` with `testing-library/await-async-events`.
** Replace `testing-library/no-await-sync-query` with `testing-library/no-await-sync-queries`.
** Replace `testing-library/no-render-in-setup` with `testing-library/no-render-in-lifecycle`.
+
* Disable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/block-spacing': 'off', // auto-fixable
            },
        },
    ],
};
----


== From v0.20.0 to v0.21.0

* If you do not use `jest`,
remove `eslint-plugin-jest`, `eslint-plugin-jest-formatting`, `eslint-plugin-jest-dom`,
and `eslint-plugin-testing-library` from `devDependencies`.
+
* If you do not use `@testing-library/jest-dom`, remove `eslint-plugin-jest-dom` from `devDependencies`.
* If you do not use `@testing-library`, remove `eslint-plugin-testing-library` from `devDependencies`.
+
* If you do not use `cypress`, remove `eslint-plugin-cypress` from `devDependencies`.
* If you do not use `rxjs`, remove `eslint-plugin-rxjs` from `devDependencies`.

[NOTE]
====
After removing optional peer dependencies, you may need to regenerate your `package-lock.json`,
as these dependencies may remain in it and in the `node_modules`.
====

* Remove the `jsdoc/newline-after-description` rule customizations,
if you have any.

* Disable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-duplicate-type-constituents': 'off',
                '@typescript-eslint/no-unsafe-enum-comparison': 'off',
                'jsdoc/imports-as-dependencies': 'off',
                'jsdoc/no-blank-blocks': 'off', // auto-fixable
                'jsdoc/tag-lines': 'off', // auto-fixable
                'unicorn/prefer-blob-reading-methods': 'off',
            },
        },
    ],
};
----


== From v0.19.0 to v0.20.0

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/key-spacing': 'off', // auto-fixable
                '@typescript-eslint/no-import-type-side-effects': 'off', // auto-fixable
                '@typescript-eslint/no-mixed-enums': 'off',
                'import/consistent-type-specifier-style': 'off', // auto-fixable
                'import/no-empty-named-blocks': 'off', // auto-fixable
                'jest/no-untyped-mock-factory': 'off', // auto-fixable
                'unicorn/no-negated-condition': 'off', // auto-fixable
                'unicorn/no-typeof-undefined': 'off', // auto-fixable
                'unicorn/refer-set-size': 'off', // auto-fixable
            },
        },
    ],
};
----


== From v0.18.0 to v0.19.0

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'logical-assignment-operators': 'off', // auto-fixable
                'no-empty-static-block': 'off',
                'no-new-native-nonconstructor': 'off',
                '@typescript-eslint/no-unsafe-declaration-merging': 'off',
                'jest/prefer-each': 'off',
                'jest/prefer-mock-promise-shorthand': 'off', // auto-fixable
                'promise/no-multiple-resolved': 'off',
                'unicorn/no-unnecessary-await': 'off', // auto-fixable
            },
        },
    ],
};
----


== From v0.17.0 to v0.18.0

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'no-constant-binary-expression': 'off',
                '@typescript-eslint/consistent-generic-constructors': 'off', // auto-fixable
                '@typescript-eslint/no-duplicate-enum-values': 'off',
                '@typescript-eslint/no-redundant-type-constituents': 'off',
                '@typescript-eslint/no-useless-empty-export': 'off', // auto-fixable
                '@typescript-eslint/parameter-properties': 'off',
                'jest/max-expects': 'off',
                'jest/prefer-hooks-in-order': 'off',
                'testing-library/no-global-regexp-flag-in-query': 'off', // auto-fixable
                'unicorn/no-unreadable-iife': 'off',
                'unicorn/no-useless-switch-case': 'off',
                'unicorn/prefer-event-target': 'off',
                'unicorn/prefer-logical-operator-over-ternary': 'off',
                'unicorn/prefer-modern-math-apis': 'off', // auto-fixable
                'unicorn/prefer-native-coercion-functions': 'off', // auto-fixable
            },
        },
    ],
};
----


== From v0.16.0 to v0.17.0

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'no-unused-private-class-members': 'off',
                'jest/no-conditional-in-test': 'off',
                // Deprecated; turn off when `jest/no-conditional-in-test` is enabled
                'jest/no-if': 'error',
                'jest/prefer-comparison-matcher': 'off',
                'jest/prefer-equality-matcher': 'off',
                'jest/prefer-snapshot-hint': 'off',
                'jsdoc/sort-tags': 'off',
                'unicorn/no-thenable': 'off',
                'unicorn/no-useless-promise-resolve-reject': 'off',
                'unicorn/prefer-json-parse-buffer': 'off',
                'unicorn/relative-url-style': 'off',
                'unicorn/text-encoding-identifier-case': 'off',
            },
        },
    ],
};
----

If you have customization of the renamed rules,
update the rules' names:

* `jest/valid-describe` into `jest/valid-describe-callback`;
* `jest/lowercase-name` into `jest/prefer-lowercase-title`;
* `testing-library/no-debug` into `testing-library/no-debugging-utils`


== From v0.15.1 to v0.16.0

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-meaningless-void-operator': 'off',
                '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'off',
                '@typescript-eslint/prefer-return-this-type': 'off',
                'cypress/no-pause': 'off',
                'jest/max-nested-describe': 'off',
                'jest/prefer-expect-resolves': 'off',
                'jest/prefer-to-be': 'off',
                'jest/require-hook': 'off',
                'jest/valid-expect-in-promise': 'off',
                'sonarjs/no-empty-collection': 'off',
                'sonarjs/no-gratuitous-expressions': 'off',
                'sonarjs/no-ignored-return': 'off',
                'sonarjs/no-inverted-boolean-check': 'off',
                'sonarjs/no-nested-switch': 'off',
                'sonarjs/no-nested-template-literals': 'off',
                'sonarjs/non-existent-operator': 'off',
                'testing-library/prefer-query-by-disappearance': 'off',
                'unicorn/no-await-expression-member': 'off',
                'unicorn/no-empty-file': 'off',
                'unicorn/no-invalid-remove-event-listener': 'off',
                'unicorn/no-useless-fallback-in-spread': 'off',
                'unicorn/no-useless-length-check': 'off',
                'unicorn/no-useless-spread': 'off',
                'unicorn/prefer-code-point': 'off',
                'unicorn/prefer-export-from': 'off',
                'unicorn/template-indent': 'off',
            },
        },
    ],
};
----
