= Migration Guide

Migration between minor versions follows the same steps:

. Update `@perfective/eslint-config` and its peer dependencies.
. Disable all new rules.
. Gradually enable the new rules:
** remove one or more rules from the list;
** fix errors or check auto-fixes of warnings;
** check for the regressions.

== From `v0.20.0` to `v0.21.0-beta.3` (next)

* If you do not use `jest`,
remove `eslint-plugin-jest`, `eslint-plugin-jest-formatting`, `eslint-plugin-jest-dom`,
and `eslint-plugin-testing-library` from `devDependencies`.
+
* If you do not use `@testing-library/jest-dom`, remove `eslint-plugin-jest-dom` from `devDependencies`.
* If you do not use `@testing-library`, remove `eslint-plugin-testing-library` from `devDependencies`.
+
* If you do not use `cypress`, remove `eslint-plugin-cypress` from `devDependencies`.
* If you do not use `rxjs`, remove `eslint-plugin-rxjs` from `devDependencies`.

[NOTE]
====
After removing optional peer dependencies, you may need to regenerate your `package-lock.json`,
as these dependencies may remain in it and in the `node_modules`.
====

* Remove the `jsdoc/newline-after-description` rule customizations,
if you have any.

* Disable new rules in the `.eslintrc.js`.
+
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-duplicate-type-constituents': 'off',
                '@typescript-eslint/no-unsafe-enum-comparison': 'off',
                'jsdoc/imports-as-dependencies': 'off',
                'jsdoc/no-blank-blocks': 'off', // auto-fixable
                'jsdoc/tag-lines': 'off', // auto-fixable
                'unicorn/prefer-blob-reading-methods': 'off',
            },
        },
    ],
};
----


== From `v0.19.0` to `v0.20.0`

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/key-spacing': 'off', // auto-fixable
                '@typescript-eslint/no-import-type-side-effects': 'off', // auto-fixable
                '@typescript-eslint/no-mixed-enums': 'off',
                'import/consistent-type-specifier-style': 'off', // auto-fixable
                'import/no-empty-named-blocks': 'off', // auto-fixable
                'jest/no-untyped-mock-factory': 'off', // auto-fixable
                'unicorn/no-negated-condition': 'off', // auto-fixable
                'unicorn/no-typeof-undefined': 'off', // auto-fixable
                'unicorn/refer-set-size': 'off', // auto-fixable
            },
        },
    ],
};
----


== From `v0.18.0` to `v0.19.0`

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'logical-assignment-operators': 'off', // auto-fixable
                'no-empty-static-block': 'off',
                'no-new-native-nonconstructor': 'off',
                '@typescript-eslint/no-unsafe-declaration-merging': 'off',
                'jest/prefer-each': 'off',
                'jest/prefer-mock-promise-shorthand': 'off', // auto-fixable
                'promise/no-multiple-resolved': 'off',
                'unicorn/no-unnecessary-await': 'off', // auto-fixable
            },
        },
    ],
};
----


== From `v0.17.0` to `v0.18.0`

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'no-constant-binary-expression': 'off',
                '@typescript-eslint/consistent-generic-constructors': 'off', // auto-fixable
                '@typescript-eslint/no-duplicate-enum-values': 'off',
                '@typescript-eslint/no-redundant-type-constituents': 'off',
                '@typescript-eslint/no-useless-empty-export': 'off', // auto-fixable
                '@typescript-eslint/parameter-properties': 'off',
                'jest/max-expects': 'off',
                'jest/prefer-hooks-in-order': 'off',
                'testing-library/no-global-regexp-flag-in-query': 'off', // auto-fixable
                'unicorn/no-unreadable-iife': 'off',
                'unicorn/no-useless-switch-case': 'off',
                'unicorn/prefer-event-target': 'off',
                'unicorn/prefer-logical-operator-over-ternary': 'off',
                'unicorn/prefer-modern-math-apis': 'off', // auto-fixable
                'unicorn/prefer-native-coercion-functions': 'off', // auto-fixable
            },
        },
    ],
};
----


== From `v0.16.0` to `v0.17.0`

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                'no-unused-private-class-members': 'off',
                'jest/no-conditional-in-test': 'off',
                // Deprecated; turn off when `jest/no-conditional-in-test` is enabled
                'jest/no-if': 'error',
                'jest/prefer-comparison-matcher': 'off',
                'jest/prefer-equality-matcher': 'off',
                'jest/prefer-snapshot-hint': 'off',
                'jsdoc/sort-tags': 'off',
                'unicorn/no-thenable': 'off',
                'unicorn/no-useless-promise-resolve-reject': 'off',
                'unicorn/prefer-json-parse-buffer': 'off',
                'unicorn/relative-url-style': 'off',
                'unicorn/text-encoding-identifier-case': 'off',
            },
        },
    ],
};
----

If you have customization of the renamed rules,
update the rules' names:

* `jest/valid-describe` into `jest/valid-describe-callback`;
* `jest/lowercase-name` into `jest/prefer-lowercase-title`;
* `testing-library/no-debug` into `testing-library/no-debugging-utils`


== From `v0.15.1` to `v0.16.0`

.Disable new rules in the `.eslintrc.js`
[source,js]
----
module.exports = {
    extends: [
        '@perfective/eslint-config',
    ],
    overrides: [
        {
            files: ['*.[jt]s?(x)'],
            rules: {
                '@typescript-eslint/no-meaningless-void-operator': 'off',
                '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'off',
                '@typescript-eslint/prefer-return-this-type': 'off',
                'cypress/no-pause': 'off',
                'jest/max-nested-describe': 'off',
                'jest/prefer-expect-resolves': 'off',
                'jest/prefer-to-be': 'off',
                'jest/require-hook': 'off',
                'jest/valid-expect-in-promise': 'off',
                'sonarjs/no-empty-collection': 'off',
                'sonarjs/no-gratuitous-expressions': 'off',
                'sonarjs/no-ignored-return': 'off',
                'sonarjs/no-inverted-boolean-check': 'off',
                'sonarjs/no-nested-switch': 'off',
                'sonarjs/no-nested-template-literals': 'off',
                'sonarjs/non-existent-operator': 'off',
                'testing-library/prefer-query-by-disappearance': 'off',
                'unicorn/no-await-expression-member': 'off',
                'unicorn/no-empty-file': 'off',
                'unicorn/no-invalid-remove-event-listener': 'off',
                'unicorn/no-useless-fallback-in-spread': 'off',
                'unicorn/no-useless-length-check': 'off',
                'unicorn/no-useless-spread': 'off',
                'unicorn/prefer-code-point': 'off',
                'unicorn/prefer-export-from': 'off',
                'unicorn/template-indent': 'off',
            },
        },
    ],
};
----
