= Perfective ESLint Config

`@perfective/eslint-config` provides
a https://eslint.org/docs/developer-guide/shareable-configs[shareable ESLint configuration]
that is used for the development of the `@perfective` packages.
As the `@perfective` library itself,
these rules are configured for the TypeScript projects only.

In addition to the core https://eslint.org/docs/rules/[ESLint rules]
and the `link:https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin[@typescript-eslint]` plugin rules,
`@perfective/eslint-config` configures:

* `link:https://github.com/freaktechnik/eslint-plugin-array-func[eslint-plugin-array-func]`;
* `link:https://github.com/gund/eslint-plugin-deprecation[eslint-plugin-deprecation]`;
* `link:https://mysticatea.github.io/eslint-plugin-eslint-comments[eslint-plugin-eslint-comments]`;
* `link:https://github.com/benmosher/eslint-plugin-import[eslint-plugin-import]`;
* `link:https://github.com/jest-community/eslint-plugin-jest[eslint-plugin-jest]`;
* `link:https://github.com/dangreenisrael/eslint-plugin-jest-formatting[eslint-plugin-jest-formatting]`;
* `link:https://github.com/gajus/eslint-plugin-jsdoc[eslint-plugin-jsdoc]`;
* `link:https://github.com/mysticatea/eslint-plugin-node[eslint-plugin-node]`;
* `link:https://github.com/TristonJ/eslint-plugin-prefer-arrow[eslint-plugin-prefer-arrow]`;
* `link:https://github.com/xjamundx/eslint-plugin-promise[eslint-plugin-promise]`;
* `link:https://github.com/cartant/eslint-plugin-rxjs[eslint-plugin-rxjs]`;
* `link:https://github.com/lydell/eslint-plugin-simple-import-sort[eslint-plugin-simple-import-sort]`;
* `link:https://github.com/SonarSource/eslint-plugin-sonarjs[eslint-plugin-sonarjs]`;
* `link:https://github.com/sindresorhus/eslint-plugin-unicorn[eslint-plugin-unicorn]`.

To simplify configuring ESLint support in the IDEs and editors,
the severity of all fixable rules is `warning`.
That allows to visually distinguish errors that have to be fixed manually
from issues that will be fixed automatically.


== Setup

. Require `@perfective/eslint-config` and its peer dependencies as dev dependencies
+
[source,bash]
----
npm install --save-dev \
    @perfective/eslint-config \
    @typescript-eslint/eslint-plugin \
    @typescript-eslint/eslint-plugin-tslint \
    @typescript-eslint/parser \
    eslint \
    eslint-import-resolver-typescript \
    eslint-plugin-array-func \
    eslint-plugin-deprecation \
    eslint-plugin-eslint-comments \
    eslint-plugin-import \
    eslint-plugin-jest \
    eslint-plugin-jest-formatting \
    eslint-plugin-jsdoc \
    eslint-plugin-node \
    eslint-plugin-prefer-arrow \
    eslint-plugin-promise \
    eslint-plugin-rxjs \
    eslint-plugin-simple-import-sort \
    eslint-plugin-sonarjs \
    eslint-plugin-unicorn \
    tslint
----
+
. Require the configuration in your root `.eslintrc.js` or `.eslintrc.json`.
+
[source,json]
----
{
    "extends": ["@perfective"]
}
----
+
. `*.d.ts` files and `dist` directories are ignored by the configuration.
`node_modules` and dot-files are ignored by the `eslint`.
If more directories or file-types need to be ignored, see the
`link:https://eslint.org/docs/user-guide/configuring/ignoring-code#the-eslintignore-file[.eslintignore]` file docs.


== Community Configuration

As the default config may seem too strict,
the package also provides a slightly relaxed `community` configuration.
Some settings used in the `community` config may be eventually migrated into the default config.

.Using community config in the `.eslintrc.json`.
[source,json]
----
{
    "extends": ["@perfective/eslint-config/community"]
}
----


== Rules Configuration Extension Functions

Some rules have complex configuration objects or arrays
that are not merged but completely overridden by ESLint.
It requires to copy/paste a rule config, instead of just extending it.
This is a challenge to maintain rules updates,
which is solved by providing custom config functions.

These functions and their related types are exported in `@perfective/eslint-config/rules`
and match the rule name in `camelCase`.
When an extended configuration is needed,
it can be applied in the `.eslintrc.js` file:

[source,javascript]
----
const rules = require('@perfective/eslint-config/rules'); // <.>

module.exports = {
    extends: ['@perfective/eslint-config'],
    rules: {
        'simple-import-sort/imports': ['warn', rules.simpleImportSortImports([
            '@perfective',
        ])],
    },
};
----
<1> Framework-specific packages, based on `@perfective/eslint-config`, re-export all the rules.
So rules should be required from those packages for correct `node_modules` resolution.

=== Supported Rules

* `simpleImportSortImports(internal)`
— allows to splice `internal` scope packages imports sorting
for the `simple-import-sort/imports` rule.
* `typescriptEslintNamingConvention(extensions)`
— extends configuration for the `@typescript-eslint/naming-convention` rule.
* `typescriptEslintTslintConfig(rules, directories)`
— overrides `rules` and provides custom `directories`
for the `@typescript-eslint/tslint/config` rule.
* `unicornPreventAbbreviations(replacements, options)`
— extends and overrides the list of `replacements`,
and override `options` for the `unicorn/prevent-abbreviation` rule.


== TSLint

ESLint and its plugins replace most of the https://palantir.github.io/tslint/[TSLint] rules.
Yet, there are few rules that still need to be supported.
TSLint rules are executed using the
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint[ESLint Plugin TSLint].

`eslint-plugin-tslint` provides only one rule `@typescript-eslint/tslint/config`
that configures all the remaining TSLint rules,
so in order to override some of them,
use the `typescriptEslintTslintConfig()` config function from the '@perfective/eslint-config/rules':

[source,typescript]
----
import { typescriptEslintTslintConfig } from '@perfective/eslint-config/rules';

export = {
    rules: {
        '@typescript-eslint/tslint/config': ['error', typescriptEslintTslintConfig({
            'no-default-import': false, // <.>
        })],
    }
}
----
<1> Overriding only one of the rules,
while keeping all others set by default.


== Internals

Rule for each plugin are described in the `./src/rules/{plugin}` subdirectories,
where `plugin` is the name of the plugin (`eslint-plugin-` prefix).
Each configuration is exported from the `./index.ts` file
and is organized as a partial ESLint config.
It should contain the plugin name and the list of the rules, sorted alphabetically.
When a plugin's documentation groups rules,
each group is configured in its own file
and then extended in the `./index.ts` file.

The final configuration extends each plugin configuration on the file-type basis.


== Roadmap

* Add `@perfective/eslint-plugin` with the rules for working with the `@perfective` library.
* Replace all TSLint rules with ESLint rules.


== Legacy

Starting from version `0.11.0` the project was extracted into its own repository
`link:https://github.com/perfective/eslint-config[@perfective/eslint-config]` from the original
`link:https://github.com/perfective/js[@perfective/js]` monorepo.
Its Git repository was rebuilt using `git filter-branch` to preserve commit log.
Legacy commits cannot be used for rollbacks and debug,
as there is no `package-lock.json`.
